site_name: Movie serial docs
# site_url: localhost/en/
# theme: readthedocs
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tooltips
    - content.tabs.link
    - content.code.copy
    - content.code.annotation
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      # primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      # primary: teal
      accent: lime

extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: فارسی
      link: /fa/
      lang: fa
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/adelkhedri

extra_css:
  - stylesheets/lang.css